name: flutter_screenshot
description: Flutter screenshot originally from screenshot package by extend more methods.
version: 0.1.0
homepage: https://github.com/kechankrisna/flutter_screenshot

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.5    

dev_dependencies:
  flutter_test:
    sdk: flutter